modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issues}"
license = "${mod_license}"
logoFile = "${mod_icon}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "CLIENT"


[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange="${version_range}"